# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-10 21:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jump_group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('groupname', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u7ec4\u540d\u79f0')),
                ('dev_list', models.CharField(blank=True, max_length=9999, null=True, verbose_name='\u673a\u5668')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '\u673a\u5668\u5206\u7ec4\u8868',
                'verbose_name_plural': '\u673a\u5668\u5206\u7ec4\u8868',
            },
        ),
        migrations.CreateModel(
            name='Jump_logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('file_path', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u65e5\u5fd7\u6587\u4ef6\u8def\u5f84')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237\u540d')),
            ],
            options={
                'verbose_name': '\u65e5\u5fd7\u8868',
                'verbose_name_plural': '\u65e5\u5fd7\u8868',
            },
        ),
        migrations.CreateModel(
            name='Jump_Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name=b'\xe9\x80\x9a\xe7\x9f\xa5\xe5\x86\x85\xe5\xae\xb9')),
                ('status', models.IntegerField(verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81')),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u901a\u77e5\u8868',
                'verbose_name_plural': '\u901a\u77e5\u8868',
            },
        ),
        migrations.CreateModel(
            name='Jump_prem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jump.Jump_group', verbose_name='\u7ed1\u5b9a\u7ec4')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237\u540d')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u6743\u9650\u7ed1\u5b9a\u8868',
                'verbose_name_plural': '\u7528\u6237\u6743\u9650\u7ed1\u5b9a\u8868',
            },
        ),
        migrations.CreateModel(
            name='Jump_user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u8d26\u6237\u540d\u79f0')),
                ('password', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u8d26\u6237\u5bc6\u7801')),
                ('permiss', models.TextField(verbose_name='sudo\u6743\u9650')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '\u8fdc\u7a0b\u8d26\u6237\u8868',
                'verbose_name_plural': '\u8fdc\u7a0b\u8d26\u6237\u8868',
            },
        ),
        migrations.AddField(
            model_name='jump_group',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jump.Jump_user', verbose_name='\u7ed1\u5b9a\u8d26\u53f7'),
        ),
    ]
